---
name: 'Debug workflow'
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Debug
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - run: npm install
      - run: npm run build
      - uses: ./.github/actions/debug-action
        id: debug
        with:
          amazing-creature: Octocat
      - run: echo There was an amazing message - ${{ steps.debug.outputs.amazing-message }}
